# Site settings
title: 19 Million Project - BBC News Labs
description: > # this means to ignore newlines until "baseurl:"
  Resources for the 19 Million project event in Rome
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: BBC_News_Labs
github_username: BBC_News_Labs

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  resources:
    output: true
    permalink: /resources/:path/

